### ISSUE TITLE
请问能分享 dnbwg-qemu-scripts  这些虚拟机的镜像吗？

### ISSUE THREAD

**Issue by fxrj** [pengan1987/dnbwg-qemu-scripts#1]
**请问能分享 dnbwg-qemu-scripts  这些虚拟机的镜像吗？** 通过no-vnc访问有些虚拟机时，鼠标无法移动到桌面的左侧部分。

**Comment by pengan1987** [comment]
我这儿上传速度慢，qcow文件太大了，所有系统的iso安装盘文件可以在互联网档案馆找到
Turbo Linux 3.0.2 https://archive.org/details/tlc302
Xteam Linux 1.0 https://archive.org/details/xteamlinux1.0
Red Flag Linux 2.0 https://archive.org/details/redflaglinux20desktop
BluePoint Linux 2.0 https://archive.org/details/bluepointlinux2
Happy Linux 1.0 https://archive.org/details/happylinux1
Chinese Linux Extensions v0.9p1 https://archive.org/details/cle09p1
安装时请使用QEMU的Cirrus Logic显卡模拟，如果遇到显示不正常，请启用XFree86的`noaccel`或`sw_cursor`选项，可参考：
https://www.xfree86.org/3.3.6/cirrus3.html
